//! # Brain Ganglia (Basal Ganglia)
//!
//! Habit engine — pattern detection and proactive behavior.
//!
//! Detects behavioral patterns by bucketing episodic memory into
//! (keyword, day-of-week, hour) histograms.  When a pattern crosses the
//! occurrence threshold at the current time slot, and rate-limit / quiet-hour
//! gates pass, a proactive message is emitted.

use chrono::{DateTime, Datelike, NaiveTime, Timelike, Utc};
use rusqlite::OptionalExtension;
use serde::{Deserialize, Serialize};
use storage::SqlitePool;
use thiserror::Error;

// ─── Errors ──────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum GangliaError {
    #[error("Storage error: {0}")]
    Storage(#[from] storage::sqlite::SqliteError),
}

// ─── Types ────────────────────────────────────────────────────────────────────

/// A recurring topic pattern detected in episodic memory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicPattern {
    /// The recurring keyword.
    pub topic: String,
    /// Day-of-week (0 = Monday, 6 = Sunday).
    pub day_of_week: u8,
    /// Hour-of-day bucket (0–23).
    pub hour: u8,
    /// Number of episodes that confirm this pattern.
    pub occurrences: usize,
}

/// A proactive message generated by the habit engine.
#[derive(Debug, Clone)]
pub struct ProactiveMessage {
    /// Message to surface to the user.
    pub content: String,
    /// The topic that triggered the message.
    pub triggered_by: String,
    /// Generation timestamp.
    pub created_at: DateTime<Utc>,
}

// ─── Config ───────────────────────────────────────────────────────────────────

/// Habit engine configuration (mirrors `core::ProactivityConfig`).
#[derive(Debug, Clone)]
pub struct HabitConfig {
    /// Maximum proactive messages per UTC calendar day.
    pub max_per_day: u32,
    /// Minimum minutes between consecutive proactive messages.
    pub min_interval_minutes: u32,
    /// Quiet-hours start (HH:MM, UTC).  No messages during this window.
    pub quiet_start: String,
    /// Quiet-hours end (HH:MM, UTC).
    pub quiet_end: String,
    /// Minimum observations before a pattern is considered stable.
    pub min_occurrences: usize,
    /// How many days back to scan for patterns.
    pub lookback_days: u32,
}

impl Default for HabitConfig {
    fn default() -> Self {
        Self {
            max_per_day: 5,
            min_interval_minutes: 60,
            quiet_start: "22:00".to_string(),
            quiet_end: "08:00".to_string(),
            min_occurrences: 3,
            lookback_days: 30,
        }
    }
}

// ─── HabitEngine ─────────────────────────────────────────────────────────────

/// Detects behavioral patterns in episodic memory and emits proactive messages.
pub struct HabitEngine {
    db: SqlitePool,
    config: HabitConfig,
}

impl HabitEngine {
    /// Create a new habit engine backed by the given SQLite pool.
    pub fn new(db: SqlitePool, config: HabitConfig) -> Self {
        Self { db, config }
    }

    /// Create the `habit_state` key-value table (idempotent).
    pub fn ensure_tables(&self) -> Result<(), GangliaError> {
        self.db.with_conn(|conn| {
            conn.execute_batch(
                "CREATE TABLE IF NOT EXISTS habit_state (
                    key   TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                );",
            )?;
            Ok(())
        })?;
        Ok(())
    }

    // ── Pattern detection ────────────────────────────────────────────────────

    /// Scan episodic memory for recurring (keyword, day-of-week, hour) patterns.
    ///
    /// Returns patterns ordered by occurrence count descending.
    pub fn detect_patterns(&self) -> Result<Vec<TopicPattern>, GangliaError> {
        use std::collections::{HashMap, HashSet};

        let cutoff = Utc::now() - chrono::Duration::days(self.config.lookback_days as i64);
        let cutoff_str = cutoff.to_rfc3339();

        let rows: Vec<(String, String)> = self.db.with_conn(|conn| {
            let mut stmt = conn.prepare(
                "SELECT content, timestamp FROM episodes
                 WHERE timestamp >= ?1
                 ORDER BY timestamp ASC",
            )?;
            let rows = stmt
                .query_map([&cutoff_str], |row| {
                    Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
                })?
                .collect::<Result<Vec<_>, _>>()?;
            Ok(rows)
        })?;

        const STOPWORDS: &[&str] = &[
            "i", "me", "my", "the", "a", "an", "is", "are", "was", "were", "be", "been",
            "being", "have", "has", "had", "do", "does", "did", "will", "would", "shall",
            "should", "may", "might", "must", "can", "could", "to", "of", "in", "on", "at",
            "for", "with", "by", "from", "that", "this", "it", "its", "and", "or", "but",
            "not", "no", "about", "what", "how", "when", "where", "who", "which", "brain",
            "remember", "recall", "store", "fact", "help", "also", "just", "then", "than",
        ];

        // (keyword, day_of_week, hour) → occurrence count
        let mut counts: HashMap<(String, u8, u8), usize> = HashMap::new();

        for (content, timestamp) in &rows {
            let dt = DateTime::parse_from_rfc3339(timestamp)
                .map(|d| d.with_timezone(&Utc))
                .unwrap_or_else(|_| Utc::now());

            let dow = dt.weekday().num_days_from_monday() as u8;
            let hour = dt.hour() as u8;

            // Use unique keywords per episode to avoid duplicate inflation
            let mut seen: HashSet<String> = HashSet::new();
            for word in content.split_whitespace() {
                let kw = word
                    .trim_matches(|c: char| !c.is_alphanumeric())
                    .to_lowercase();
                if kw.len() >= 4
                    && !STOPWORDS.contains(&kw.as_str())
                    && seen.insert(kw.clone())
                {
                    *counts.entry((kw, dow, hour)).or_insert(0) += 1;
                }
            }
        }

        let mut patterns: Vec<TopicPattern> = counts
            .into_iter()
            .filter(|(_, count)| *count >= self.config.min_occurrences)
            .map(|((topic, day_of_week, hour), occurrences)| TopicPattern {
                topic,
                day_of_week,
                hour,
                occurrences,
            })
            .collect();

        patterns.sort_by(|a, b| b.occurrences.cmp(&a.occurrences));
        Ok(patterns)
    }

    // ── Rate limiting ─────────────────────────────────────────────────────────

    /// Returns `true` if the current UTC time is within quiet hours.
    pub fn is_quiet_time(&self) -> bool {
        let now = Utc::now();
        let current = NaiveTime::from_hms_opt(now.hour(), now.minute(), 0).unwrap_or_default();

        let parse = |s: &str| NaiveTime::parse_from_str(s, "%H:%M").unwrap_or_default();
        let start = parse(&self.config.quiet_start);
        let end = parse(&self.config.quiet_end);

        if start <= end {
            current >= start && current < end
        } else {
            // Overnight window e.g. 22:00–08:00
            current >= start || current < end
        }
    }

    /// Returns the number of proactive messages sent today (UTC calendar day).
    fn daily_sent_count(&self) -> Result<u32, GangliaError> {
        let today = Utc::now().format("%Y-%m-%d").to_string();

        let stored_date: Option<String> = self.db.with_conn(|conn| {
            conn.query_row(
                "SELECT value FROM habit_state WHERE key = 'daily_sent_date'",
                [],
                |row| row.get::<_, String>(0),
            )
            .optional()
            .map_err(|e| e.into())
        })?;

        if stored_date.as_deref() != Some(today.as_str()) {
            return Ok(0);
        }

        let count: u32 = self.db.with_conn(|conn| {
            conn.query_row(
                "SELECT value FROM habit_state WHERE key = 'daily_sent_count'",
                [],
                |row| row.get::<_, String>(0),
            )
            .optional()
            .map(|v| v.and_then(|s| s.parse::<u32>().ok()).unwrap_or(0))
            .map_err(|e| e.into())
        })?;

        Ok(count)
    }

    /// Returns minutes elapsed since the last proactive message was sent.
    /// Returns `u32::MAX` if no message has ever been sent.
    fn minutes_since_last_sent(&self) -> Result<u32, GangliaError> {
        let ts: Option<String> = self.db.with_conn(|conn| {
            conn.query_row(
                "SELECT value FROM habit_state WHERE key = 'last_sent_at'",
                [],
                |row| row.get::<_, String>(0),
            )
            .optional()
            .map_err(|e| e.into())
        })?;

        match ts {
            None => Ok(u32::MAX),
            Some(s) => {
                let last = DateTime::parse_from_rfc3339(&s)
                    .map(|d| d.with_timezone(&Utc))
                    .unwrap_or_else(|_| Utc::now() - chrono::Duration::hours(25));
                let mins = (Utc::now() - last).num_minutes().max(0) as u32;
                Ok(mins)
            }
        }
    }

    /// Persist a proactive send event — increments daily counter and records timestamp.
    pub fn record_sent(&self) -> Result<(), GangliaError> {
        let today = Utc::now().format("%Y-%m-%d").to_string();
        let now = Utc::now().to_rfc3339();
        let new_count = self.daily_sent_count()? + 1;

        self.db.with_conn(|conn| {
            conn.execute(
                "INSERT INTO habit_state (key, value) VALUES ('daily_sent_date', ?1)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                [&today],
            )?;
            conn.execute(
                "INSERT INTO habit_state (key, value) VALUES ('daily_sent_count', ?1)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                [&new_count.to_string()],
            )?;
            conn.execute(
                "INSERT INTO habit_state (key, value) VALUES ('last_sent_at', ?1)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                [&now],
            )?;
            Ok(())
        })?;
        Ok(())
    }

    /// Returns `true` if all rate-limit and quiet-hour gates are open.
    pub fn can_send_proactive(&self) -> Result<bool, GangliaError> {
        if self.is_quiet_time() {
            return Ok(false);
        }
        if self.daily_sent_count()? >= self.config.max_per_day {
            return Ok(false);
        }
        if self.minutes_since_last_sent()? < self.config.min_interval_minutes {
            return Ok(false);
        }
        Ok(true)
    }

    // ── Main entry point ──────────────────────────────────────────────────────

    /// Generate a proactive message if conditions are met.
    ///
    /// Detects patterns in recent episodic memory, checks whether the current
    /// time matches a known pattern slot, and verifies rate-limit / quiet-hour
    /// gates before returning a message.  Returns `None` when no action is needed.
    pub fn generate_proactive(&self) -> Result<Option<ProactiveMessage>, GangliaError> {
        if !self.can_send_proactive()? {
            return Ok(None);
        }

        let now = Utc::now();
        let current_dow = now.weekday().num_days_from_monday() as u8;
        let current_hour = now.hour() as u8;

        let patterns = self.detect_patterns()?;

        let matching = patterns
            .into_iter()
            .find(|p| p.day_of_week == current_dow && p.hour == current_hour);

        if let Some(pattern) = matching {
            self.record_sent()?;
            Ok(Some(ProactiveMessage {
                content: format!(
                    "You usually work on \"{}\" around this time. \
                     Want to review or update anything?",
                    pattern.topic
                ),
                triggered_by: pattern.topic.clone(),
                created_at: now,
            }))
        } else {
            Ok(None)
        }
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn test_engine() -> HabitEngine {
        let pool = storage::SqlitePool::open_memory().unwrap();
        let engine = HabitEngine::new(pool, HabitConfig::default());
        engine.ensure_tables().unwrap();
        engine
    }

    #[test]
    fn test_ensure_tables_idempotent() {
        let engine = test_engine();
        // Second call must not error
        engine.ensure_tables().unwrap();
    }

    #[test]
    fn test_no_patterns_when_empty() {
        let engine = test_engine();
        let patterns = engine.detect_patterns().unwrap();
        assert!(patterns.is_empty());
    }

    #[test]
    fn test_can_send_when_no_history() {
        let engine = test_engine();
        // No history → daily count = 0, last_sent = never → all gates open
        // (quiet hours depend on current UTC time — we cannot guarantee them
        //  to be open in test, so only check non-quiet conditions below)
        let count = engine.daily_sent_count().unwrap();
        assert_eq!(count, 0);
        let mins = engine.minutes_since_last_sent().unwrap();
        assert_eq!(mins, u32::MAX);
    }

    #[test]
    fn test_record_sent_increments_count() {
        let engine = test_engine();
        assert_eq!(engine.daily_sent_count().unwrap(), 0);
        engine.record_sent().unwrap();
        assert_eq!(engine.daily_sent_count().unwrap(), 1);
        engine.record_sent().unwrap();
        assert_eq!(engine.daily_sent_count().unwrap(), 2);
    }

    #[test]
    fn test_record_sent_updates_last_sent() {
        let engine = test_engine();
        assert_eq!(engine.minutes_since_last_sent().unwrap(), u32::MAX);
        engine.record_sent().unwrap();
        // Should now be ~0 minutes ago
        assert!(engine.minutes_since_last_sent().unwrap() < 2);
    }

    #[test]
    fn test_quiet_time_overnight_range() {
        // Build a config with an always-active quiet window (00:00–23:59)
        // to verify the overnight path triggers.
        let engine = HabitEngine::new(
            storage::SqlitePool::open_memory().unwrap(),
            HabitConfig {
                quiet_start: "00:00".to_string(),
                quiet_end: "23:59".to_string(),
                ..Default::default()
            },
        );
        assert!(engine.is_quiet_time());
    }

    #[test]
    fn test_max_per_day_blocks_send() {
        let engine = HabitEngine::new(
            storage::SqlitePool::open_memory().unwrap(),
            HabitConfig {
                max_per_day: 1,
                // Disable quiet hours and interval so only daily cap applies
                quiet_start: "00:00".to_string(),
                quiet_end: "00:00".to_string(),
                min_interval_minutes: 0,
                ..Default::default()
            },
        );
        engine.ensure_tables().unwrap();
        engine.record_sent().unwrap(); // hit the cap

        assert!(!engine.can_send_proactive().unwrap());
    }

    #[test]
    fn test_generate_proactive_returns_none_when_no_patterns() {
        // Use a config with no quiet hours and no interval gate to isolate
        // the pattern-detection path.
        let engine = HabitEngine::new(
            storage::SqlitePool::open_memory().unwrap(),
            HabitConfig {
                quiet_start: "00:00".to_string(),
                quiet_end: "00:00".to_string(),
                min_interval_minutes: 0,
                min_occurrences: 3,
                ..Default::default()
            },
        );
        engine.ensure_tables().unwrap();
        // No episodes → no patterns → no proactive message
        let result = engine.generate_proactive().unwrap();
        assert!(result.is_none());
    }
}
