//! # Brain Ganglia (Basal Ganglia)
//!
//! Habit engine — pattern detection and proactive behavior.
//!
//! Detects behavioral patterns by bucketing episodic memory into
//! (keyword, day-of-week, hour) histograms.  When a pattern crosses the
//! occurrence threshold at the current time slot, and rate-limit / quiet-hour
//! gates pass, a proactive message is emitted.

use std::sync::Arc;

use chrono::{DateTime, Datelike, NaiveTime, Timelike, Utc};
use chrono_tz::Tz;
use rusqlite::OptionalExtension;
use serde::{Deserialize, Serialize};
use storage::SqlitePool;
use thiserror::Error;

// ─── Errors ──────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum GangliaError {
    #[error("Storage error: {0}")]
    Storage(#[from] storage::sqlite::SqliteError),
}

// ─── Types ────────────────────────────────────────────────────────────────────

/// A recurring topic pattern detected in episodic memory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicPattern {
    /// The recurring keyword.
    pub topic: String,
    /// Day-of-week (0 = Monday, 6 = Sunday).
    pub day_of_week: u8,
    /// Hour-of-day bucket (0–23).
    pub hour: u8,
    /// Number of episodes that confirm this pattern.
    pub occurrences: usize,
    /// Originating agent for this pattern (if all occurrences are from one agent).
    pub agent: Option<String>,
}

/// A proactive message generated by the habit engine.
#[derive(Debug, Clone)]
pub struct ProactiveMessage {
    /// Message to surface to the user.
    pub content: String,
    /// The topic that triggered the message.
    pub triggered_by: String,
    /// Generation timestamp.
    pub created_at: DateTime<Utc>,
    /// Originating agent (if the pattern is agent-attributed).
    pub agent: Option<String>,
}

// ─── Config ───────────────────────────────────────────────────────────────────

/// Habit engine configuration (mirrors `core::ProactivityConfig`).
#[derive(Debug, Clone)]
pub struct HabitConfig {
    /// Maximum proactive messages per UTC calendar day.
    pub max_per_day: u32,
    /// Minimum minutes between consecutive proactive messages.
    pub min_interval_minutes: u32,
    /// Quiet-hours start (HH:MM, UTC).  No messages during this window.
    pub quiet_start: String,
    /// Quiet-hours end (HH:MM, UTC).
    pub quiet_end: String,
    /// User's local timezone (e.g. "America/New_York", "Europe/London").
    pub timezone: String,
    /// Minimum observations before a pattern is considered stable.
    pub min_occurrences: usize,
    /// How many days back to scan for patterns.
    pub lookback_days: u32,
}

impl Default for HabitConfig {
    fn default() -> Self {
        Self {
            max_per_day: 5,
            min_interval_minutes: 60,
            quiet_start: "22:00".to_string(),
            quiet_end: "08:00".to_string(),
            timezone: "UTC".to_string(),
            min_occurrences: 3,
            lookback_days: 30,
        }
    }
}

// ─── HabitEngine ─────────────────────────────────────────────────────────────

/// Detects behavioral patterns in episodic memory and emits proactive messages.
pub struct HabitEngine {
    db: SqlitePool,
    config: HabitConfig,
}

impl HabitEngine {
    /// Create a new habit engine backed by the given SQLite pool.
    pub fn new(db: SqlitePool, config: HabitConfig) -> Self {
        Self { db, config }
    }

    /// Create the `habit_state` key-value table (idempotent).
    pub fn ensure_tables(&self) -> Result<(), GangliaError> {
        self.db.with_conn(|conn| {
            conn.execute_batch(
                "CREATE TABLE IF NOT EXISTS habit_state (
                    key   TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                );",
            )?;
            Ok(())
        })?;
        Ok(())
    }

    // ── Pattern detection ────────────────────────────────────────────────────

    /// Scan episodic memory for recurring (keyword, day-of-week, hour) patterns.
    ///
    /// Returns patterns ordered by occurrence count descending.
    pub fn detect_patterns(&self) -> Result<Vec<TopicPattern>, GangliaError> {
        use std::collections::{HashMap, HashSet};

        let cutoff = Utc::now() - chrono::Duration::days(self.config.lookback_days as i64);
        let cutoff_str = cutoff.to_rfc3339();

        let rows: Vec<(String, String, Option<String>)> = self.db.with_conn(|conn| {
            let mut stmt = conn.prepare(
                "SELECT content, timestamp, agent FROM episodes
                 WHERE timestamp >= ?1
                 ORDER BY timestamp ASC",
            )?;
            let rows = stmt
                .query_map([&cutoff_str], |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, String>(1)?,
                        row.get::<_, Option<String>>(2)?,
                    ))
                })?
                .collect::<Result<Vec<_>, _>>()?;
            Ok(rows)
        })?;

        const STOPWORDS: &[&str] = &[
            "i", "me", "my", "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
            "have", "has", "had", "do", "does", "did", "will", "would", "shall", "should", "may",
            "might", "must", "can", "could", "to", "of", "in", "on", "at", "for", "with", "by",
            "from", "that", "this", "it", "its", "and", "or", "but", "not", "no", "about", "what",
            "how", "when", "where", "who", "which", "brain", "remember", "recall", "store", "fact",
            "help", "also", "just", "then", "than",
        ];

        // (keyword, day_of_week, hour) → (count, agents seen)
        type PatternKey = (String, u8, u8);
        type PatternValue = (usize, HashSet<Option<String>>);
        let mut counts: HashMap<PatternKey, PatternValue> = HashMap::new();

        for (content, timestamp, agent) in &rows {
            let dt = DateTime::parse_from_rfc3339(timestamp)
                .map(|d| d.with_timezone(&Utc))
                .unwrap_or_else(|_| Utc::now());

            let dow = dt.weekday().num_days_from_monday() as u8;
            let hour = dt.hour() as u8;

            // Use unique keywords per episode to avoid duplicate inflation
            let mut seen: HashSet<String> = HashSet::new();
            for word in content.split_whitespace() {
                let kw = word
                    .trim_matches(|c: char| !c.is_alphanumeric())
                    .to_lowercase();
                if kw.len() >= 4 && !STOPWORDS.contains(&kw.as_str()) && seen.insert(kw.clone()) {
                    let entry = counts
                        .entry((kw, dow, hour))
                        .or_insert_with(|| (0, HashSet::new()));
                    entry.0 += 1;
                    entry.1.insert(agent.clone());
                }
            }
        }

        let mut patterns: Vec<TopicPattern> = counts
            .into_iter()
            .filter(|(_, (count, _))| *count >= self.config.min_occurrences)
            .map(|((topic, day_of_week, hour), (occurrences, agents))| {
                // If all occurrences come from a single known agent, attribute it
                let agent = if agents.len() == 1 {
                    agents.into_iter().next().unwrap()
                } else {
                    None
                };
                TopicPattern {
                    topic,
                    day_of_week,
                    hour,
                    occurrences,
                    agent,
                }
            })
            .collect();

        patterns.sort_by(|a, b| b.occurrences.cmp(&a.occurrences));
        Ok(patterns)
    }

    // ── Rate limiting ─────────────────────────────────────────────────────────

    /// Returns `true` if the current time in the configured timezone is within quiet hours.
    pub fn is_quiet_time(&self) -> bool {
        let tz: Tz = self.config.timezone.parse().unwrap_or(chrono_tz::UTC);
        let now = Utc::now().with_timezone(&tz);
        let current = NaiveTime::from_hms_opt(now.hour(), now.minute(), 0).unwrap_or_default();

        let parse = |s: &str| NaiveTime::parse_from_str(s, "%H:%M").unwrap_or_default();
        let start = parse(&self.config.quiet_start);
        let end = parse(&self.config.quiet_end);

        if start <= end {
            current >= start && current < end
        } else {
            // Overnight window e.g. 22:00–08:00
            current >= start || current < end
        }
    }

    /// Returns the number of proactive messages sent today (UTC calendar day).
    fn daily_sent_count(&self) -> Result<u32, GangliaError> {
        let today = Utc::now().format("%Y-%m-%d").to_string();

        let stored_date: Option<String> = self.db.with_conn(|conn| {
            conn.query_row(
                "SELECT value FROM habit_state WHERE key = 'daily_sent_date'",
                [],
                |row| row.get::<_, String>(0),
            )
            .optional()
            .map_err(|e| e.into())
        })?;

        if stored_date.as_deref() != Some(today.as_str()) {
            return Ok(0);
        }

        let count: u32 = self.db.with_conn(|conn| {
            conn.query_row(
                "SELECT value FROM habit_state WHERE key = 'daily_sent_count'",
                [],
                |row| row.get::<_, String>(0),
            )
            .optional()
            .map(|v| v.and_then(|s| s.parse::<u32>().ok()).unwrap_or(0))
            .map_err(|e| e.into())
        })?;

        Ok(count)
    }

    /// Returns minutes elapsed since the last proactive message was sent.
    /// Returns `u32::MAX` if no message has ever been sent.
    fn minutes_since_last_sent(&self) -> Result<u32, GangliaError> {
        let ts: Option<String> = self.db.with_conn(|conn| {
            conn.query_row(
                "SELECT value FROM habit_state WHERE key = 'last_sent_at'",
                [],
                |row| row.get::<_, String>(0),
            )
            .optional()
            .map_err(|e| e.into())
        })?;

        match ts {
            None => Ok(u32::MAX),
            Some(s) => {
                let last = DateTime::parse_from_rfc3339(&s)
                    .map(|d| d.with_timezone(&Utc))
                    .unwrap_or_else(|_| Utc::now() - chrono::Duration::hours(25));
                let mins = (Utc::now() - last).num_minutes().max(0) as u32;
                Ok(mins)
            }
        }
    }

    /// Persist a proactive send event — increments daily counter and records timestamp.
    pub fn record_sent(&self) -> Result<(), GangliaError> {
        let today = Utc::now().format("%Y-%m-%d").to_string();
        let now = Utc::now().to_rfc3339();
        let new_count = self.daily_sent_count()? + 1;

        self.db.with_conn(|conn| {
            conn.execute(
                "INSERT INTO habit_state (key, value) VALUES ('daily_sent_date', ?1)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                [&today],
            )?;
            conn.execute(
                "INSERT INTO habit_state (key, value) VALUES ('daily_sent_count', ?1)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                [&new_count.to_string()],
            )?;
            conn.execute(
                "INSERT INTO habit_state (key, value) VALUES ('last_sent_at', ?1)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                [&now],
            )?;
            Ok(())
        })?;
        Ok(())
    }

    /// Returns `true` if all rate-limit and quiet-hour gates are open.
    pub fn can_send_proactive(&self) -> Result<bool, GangliaError> {
        if self.is_quiet_time() {
            return Ok(false);
        }
        if self.daily_sent_count()? >= self.config.max_per_day {
            return Ok(false);
        }
        if self.minutes_since_last_sent()? < self.config.min_interval_minutes {
            return Ok(false);
        }
        Ok(true)
    }

    // ── Main entry point ──────────────────────────────────────────────────────

    /// Generate a proactive message if conditions are met.
    ///
    /// Detects patterns in recent episodic memory, checks whether the current
    /// time matches a known pattern slot, and verifies rate-limit / quiet-hour
    /// gates before returning a message.  Returns `None` when no action is needed.
    pub fn generate_proactive(&self) -> Result<Option<ProactiveMessage>, GangliaError> {
        if !self.can_send_proactive()? {
            return Ok(None);
        }

        let now = Utc::now();
        let current_dow = now.weekday().num_days_from_monday() as u8;
        let current_hour = now.hour() as u8;

        let patterns = self.detect_patterns()?;

        let matching = patterns
            .into_iter()
            .find(|p| p.day_of_week == current_dow && p.hour == current_hour);

        if let Some(pattern) = matching {
            self.record_sent()?;
            let content = if let Some(ref agent) = pattern.agent {
                format!(
                    "{} often works on \"{}\" around this time. \
                     Want to review or update anything?",
                    agent, pattern.topic
                )
            } else {
                format!(
                    "You usually work on \"{}\" around this time. \
                     Want to review or update anything?",
                    pattern.topic
                )
            };
            Ok(Some(ProactiveMessage {
                content,
                triggered_by: pattern.topic.clone(),
                created_at: now,
                agent: pattern.agent.clone(),
            }))
        } else {
            Ok(None)
        }
    }
}

// ─── Open-loop Detection ─────────────────────────────────────────────────────

/// Configuration for open-loop (unresolved commitment) detection.
#[derive(Debug, Clone)]
pub struct OpenLoopConfig {
    /// How many hours back to scan for commitments.
    pub scan_window_hours: u32,
    /// Hours after a commitment before it's flagged as unresolved.
    pub resolution_window_hours: u32,
    /// Maximum reminders to generate per check cycle.
    pub max_reminders: usize,
}

impl Default for OpenLoopConfig {
    fn default() -> Self {
        Self {
            scan_window_hours: 72,
            resolution_window_hours: 24,
            max_reminders: 3,
        }
    }
}

/// An unresolved commitment found in episodic memory.
#[derive(Debug, Clone)]
pub struct OpenLoop {
    pub commitment: String,
    pub topic: String,
    pub committed_at: String,
    pub agent: Option<String>,
}

/// Detects unresolved commitments ("open loops") in episodic memory.
///
/// Scans for commitment phrases like "I need to", "remind me to", etc.
/// and checks whether a subsequent episode references the same topic.
/// If no resolution is found within `resolution_window_hours`, a
/// reminder is surfaced.
///
/// When constructed with `with_llm()`, `detect_open_loops_async()` uses
/// LLM-driven analysis with automatic fallback to keyword heuristics.
pub struct OpenLoopDetector {
    db: SqlitePool,
    config: OpenLoopConfig,
    llm: Option<Arc<dyn cortex::LlmProvider>>,
}

/// Phrases that signal a user commitment or intention.
const COMMITMENT_PHRASES: &[&str] = &[
    "i'll",
    "i will",
    "i need to",
    "i should",
    "i must",
    "remind me to",
    "don't forget",
    "need to remember",
    "going to",
    "plan to",
    "want to",
    "have to",
    "todo",
    "to-do",
];

/// Words that signal a commitment has been resolved.
const RESOLUTION_MARKERS: &[&str] = &[
    "done",
    "finished",
    "completed",
    "did it",
    "checked off",
    "resolved",
    "took care",
    "handled",
    "sorted",
    "already",
];

/// A fetched episode row: (id, content, timestamp, agent).
type EpisodeRow = (String, String, String, Option<String>);

impl OpenLoopDetector {
    pub fn new(db: SqlitePool, config: OpenLoopConfig) -> Self {
        Self {
            db,
            config,
            llm: None,
        }
    }

    /// Create an OpenLoopDetector backed by the given LLM provider.
    pub fn with_llm(
        db: SqlitePool,
        config: OpenLoopConfig,
        llm: Arc<dyn cortex::LlmProvider>,
    ) -> Self {
        Self {
            db,
            config,
            llm: Some(llm),
        }
    }

    /// Fetch user episodes within the scan window.
    fn fetch_episodes(&self) -> Result<Vec<EpisodeRow>, GangliaError> {
        let scan_cutoff =
            Utc::now() - chrono::Duration::hours(self.config.scan_window_hours as i64);
        let scan_str = scan_cutoff.to_rfc3339();

        self.db.with_conn(|conn| {
            let mut stmt = conn.prepare(
                "SELECT id, content, timestamp, agent FROM episodes
                 WHERE timestamp >= ?1 AND role = 'user'
                 ORDER BY timestamp ASC",
            )?;
            let rows = stmt
                .query_map([&scan_str], |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, String>(1)?,
                        row.get::<_, String>(2)?,
                        row.get::<_, Option<String>>(3)?,
                    ))
                })?
                .collect::<Result<Vec<_>, _>>()?;
            Ok(rows)
        })
        .map_err(Into::into)
    }

    /// Scan episodic memory for unresolved commitments (keyword heuristic).
    pub fn detect_open_loops(&self) -> Result<Vec<OpenLoop>, GangliaError> {
        let now = Utc::now();
        let resolution_cutoff =
            now - chrono::Duration::hours(self.config.resolution_window_hours as i64);

        let episodes = self.fetch_episodes()?;

        let mut open_loops = Vec::new();

        for (id, content, timestamp, agent) in &episodes {
            let lower = content.to_lowercase();

            // Extract topic from commitment phrase
            let topic = COMMITMENT_PHRASES.iter().find_map(|phrase| {
                lower.find(phrase).map(|pos| {
                    let after = &content[pos + phrase.len()..];
                    let trimmed = after
                        .trim()
                        .trim_start_matches(|c: char| !c.is_alphanumeric());
                    trimmed
                        .split_whitespace()
                        .take(8)
                        .collect::<Vec<_>>()
                        .join(" ")
                })
            });

            let topic = match topic {
                Some(t) if t.len() >= 3 => t,
                _ => continue,
            };

            // Only flag commitments that are old enough
            let committed_dt = DateTime::parse_from_rfc3339(timestamp)
                .map(|d| d.with_timezone(&Utc))
                .unwrap_or(now);
            if committed_dt > resolution_cutoff {
                continue;
            }

            // Extract meaningful keywords from the topic for matching
            let topic_words: Vec<String> = topic
                .split_whitespace()
                .map(|w| {
                    w.trim_matches(|c: char| !c.is_alphanumeric())
                        .to_lowercase()
                })
                .filter(|w| w.len() >= 4)
                .collect();
            if topic_words.is_empty() {
                continue;
            }

            // Check if any later episode resolves this commitment
            let resolved = episodes.iter().any(|(eid, econtent, ets, _)| {
                if eid == id {
                    return false;
                }
                let edt = DateTime::parse_from_rfc3339(ets)
                    .map(|d| d.with_timezone(&Utc))
                    .unwrap_or(now);
                if edt <= committed_dt {
                    return false;
                }
                let elower = econtent.to_lowercase();

                // Check for resolution markers alongside topic words
                let has_topic_ref = topic_words
                    .iter()
                    .filter(|w| elower.contains(w.as_str()))
                    .count()
                    >= topic_words.len().clamp(1, 2);

                let has_resolution_marker = RESOLUTION_MARKERS.iter().any(|m| elower.contains(m));

                // Resolved if topic is referenced with a resolution marker,
                // or if most topic words appear (likely a follow-up)
                (has_topic_ref && has_resolution_marker)
                    || topic_words
                        .iter()
                        .filter(|w| elower.contains(w.as_str()))
                        .count()
                        >= topic_words.len().max(2)
            });

            if !resolved {
                open_loops.push(OpenLoop {
                    commitment: content.clone(),
                    topic: topic.clone(),
                    committed_at: timestamp.clone(),
                    agent: agent.clone(),
                });
            }
        }

        open_loops.truncate(self.config.max_reminders);
        Ok(open_loops)
    }

    /// Detect open loops using LLM when available, keyword fallback otherwise.
    pub async fn detect_open_loops_async(&self) -> Result<Vec<OpenLoop>, GangliaError> {
        if self.llm.is_none() {
            return self.detect_open_loops();
        }

        let episodes = self.fetch_episodes()?;
        if episodes.is_empty() {
            return Ok(Vec::new());
        }

        let llm = self.llm.as_ref().unwrap();
        let timeout = tokio::time::Duration::from_millis(2000);
        match tokio::time::timeout(timeout, self.detect_with_llm(llm, &episodes)).await {
            Ok(Ok(loops)) => Ok(loops),
            Ok(Err(e)) => {
                tracing::debug!("LLM open-loop detection failed: {e}, falling back to keywords");
                self.detect_open_loops()
            }
            Err(_) => {
                tracing::debug!("LLM open-loop detection timed out, falling back to keywords");
                self.detect_open_loops()
            }
        }
    }

    /// Ask the LLM to identify unresolved commitments.
    async fn detect_with_llm(
        &self,
        llm: &Arc<dyn cortex::LlmProvider>,
        episodes: &[EpisodeRow],
    ) -> Result<Vec<OpenLoop>, cortex::LlmError> {
        let resolution_cutoff =
            Utc::now() - chrono::Duration::hours(self.config.resolution_window_hours as i64);
        let cutoff_str = resolution_cutoff.to_rfc3339();

        // Build indexed message list for the prompt
        let mut message_lines = String::new();
        for (i, (_id, content, ts, _agent)) in episodes.iter().enumerate() {
            message_lines.push_str(&format!("[{i}] ({ts}) {content}\n"));
        }

        let prompt = format!(
            "Analyze these user messages for unresolved commitments.\n\
             A commitment is when the user says they will/need/should/plan to do something.\n\
             A commitment is resolved if a later message indicates it was done/finished/completed.\n\
             Only flag commitments older than: {cutoff_str}\n\
             Return ONLY JSON array: [{{\"index\":N,\"topic\":\"brief description\",\"resolved\":false}}]\n\
             Return [] if none found.\n\
             Messages:\n{message_lines}"
        );

        let messages = vec![cortex::Message {
            role: cortex::Role::User,
            content: prompt,
        }];

        let response = llm.generate(&messages).await?;
        let parsed = parse_commitment_response(&response.content, episodes, self.config.max_reminders)?;
        Ok(parsed)
    }

    /// Generate proactive reminder messages for unresolved commitments (keyword heuristic).
    pub fn generate_reminders(&self) -> Result<Vec<ProactiveMessage>, GangliaError> {
        let loops = self.detect_open_loops()?;
        Ok(format_reminders(loops))
    }

    /// Generate proactive reminder messages using LLM when available, keyword fallback otherwise.
    pub async fn generate_reminders_async(&self) -> Result<Vec<ProactiveMessage>, GangliaError> {
        let loops = self.detect_open_loops_async().await?;
        Ok(format_reminders(loops))
    }
}

/// Format open loops into proactive reminder messages.
fn format_reminders(loops: Vec<OpenLoop>) -> Vec<ProactiveMessage> {
    loops
        .into_iter()
        .map(|ol| {
            let content = if let Some(ref agent) = ol.agent {
                format!(
                    "Open loop from {}: you mentioned \"{}\" — still pending. Want to follow up?",
                    agent, ol.topic
                )
            } else {
                format!(
                    "Open loop: you mentioned \"{}\" — still pending. Want to follow up?",
                    ol.topic
                )
            };
            ProactiveMessage {
                content,
                triggered_by: format!("open_loop:{}", ol.topic),
                created_at: Utc::now(),
                agent: ol.agent,
            }
        })
        .collect()
}

/// Parse LLM response into OpenLoop entries. Tries direct JSON, then finds `[...]`.
fn parse_commitment_response(
    raw: &str,
    episodes: &[EpisodeRow],
    max_reminders: usize,
) -> Result<Vec<OpenLoop>, cortex::LlmError> {
    #[derive(Deserialize)]
    struct CommitmentEntry {
        index: usize,
        topic: String,
        #[serde(default)]
        resolved: bool,
    }

    let trimmed = raw.trim();

    // Try direct parse
    let entries: Vec<CommitmentEntry> =
        if let Ok(parsed) = serde_json::from_str::<Vec<CommitmentEntry>>(trimmed) {
            parsed
        } else if let Some(start) = trimmed.find('[') {
            if let Some(end) = trimmed.rfind(']') {
                serde_json::from_str::<Vec<CommitmentEntry>>(&trimmed[start..=end]).map_err(
                    |e| {
                        cortex::LlmError::InvalidFormat(format!(
                            "Could not parse commitment JSON: {e}"
                        ))
                    },
                )?
            } else {
                return Err(cortex::LlmError::InvalidFormat(
                    "No closing bracket in commitment response".to_string(),
                ));
            }
        } else {
            return Err(cortex::LlmError::InvalidFormat(
                "No JSON array in commitment response".to_string(),
            ));
        };

    let mut loops: Vec<OpenLoop> = entries
        .into_iter()
        .filter(|e| !e.resolved && e.index < episodes.len())
        .map(|e| {
            let (_, content, ts, agent) = &episodes[e.index];
            OpenLoop {
                commitment: content.clone(),
                topic: e.topic,
                committed_at: ts.clone(),
                agent: agent.clone(),
            }
        })
        .collect();

    loops.truncate(max_reminders);
    Ok(loops)
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn test_engine() -> HabitEngine {
        let pool = storage::SqlitePool::open_memory().unwrap();
        let engine = HabitEngine::new(pool, HabitConfig::default());
        engine.ensure_tables().unwrap();
        engine
    }

    #[test]
    fn test_ensure_tables_idempotent() {
        let engine = test_engine();
        // Second call must not error
        engine.ensure_tables().unwrap();
    }

    #[test]
    fn test_no_patterns_when_empty() {
        let engine = test_engine();
        let patterns = engine.detect_patterns().unwrap();
        assert!(patterns.is_empty());
    }

    #[test]
    fn test_can_send_when_no_history() {
        let engine = test_engine();
        // No history → daily count = 0, last_sent = never → all gates open
        // (quiet hours depend on current UTC time — we cannot guarantee them
        //  to be open in test, so only check non-quiet conditions below)
        let count = engine.daily_sent_count().unwrap();
        assert_eq!(count, 0);
        let mins = engine.minutes_since_last_sent().unwrap();
        assert_eq!(mins, u32::MAX);
    }

    #[test]
    fn test_record_sent_increments_count() {
        let engine = test_engine();
        assert_eq!(engine.daily_sent_count().unwrap(), 0);
        engine.record_sent().unwrap();
        assert_eq!(engine.daily_sent_count().unwrap(), 1);
        engine.record_sent().unwrap();
        assert_eq!(engine.daily_sent_count().unwrap(), 2);
    }

    #[test]
    fn test_record_sent_updates_last_sent() {
        let engine = test_engine();
        assert_eq!(engine.minutes_since_last_sent().unwrap(), u32::MAX);
        engine.record_sent().unwrap();
        // Should now be ~0 minutes ago
        assert!(engine.minutes_since_last_sent().unwrap() < 2);
    }

    #[test]
    fn test_quiet_time_overnight_range() {
        // Build a config with an always-active quiet window (00:00–23:59)
        // to verify the overnight path triggers.
        let engine = HabitEngine::new(
            storage::SqlitePool::open_memory().unwrap(),
            HabitConfig {
                quiet_start: "00:00".to_string(),
                quiet_end: "23:59".to_string(),
                ..Default::default()
            },
        );
        assert!(engine.is_quiet_time());
    }

    #[test]
    fn test_max_per_day_blocks_send() {
        let engine = HabitEngine::new(
            storage::SqlitePool::open_memory().unwrap(),
            HabitConfig {
                max_per_day: 1,
                // Disable quiet hours and interval so only daily cap applies
                quiet_start: "00:00".to_string(),
                quiet_end: "00:00".to_string(),
                min_interval_minutes: 0,
                ..Default::default()
            },
        );
        engine.ensure_tables().unwrap();
        engine.record_sent().unwrap(); // hit the cap

        assert!(!engine.can_send_proactive().unwrap());
    }

    #[test]
    fn test_generate_proactive_returns_none_when_no_patterns() {
        // Use a config with no quiet hours and no interval gate to isolate
        // the pattern-detection path.
        let engine = HabitEngine::new(
            storage::SqlitePool::open_memory().unwrap(),
            HabitConfig {
                quiet_start: "00:00".to_string(),
                quiet_end: "00:00".to_string(),
                min_interval_minutes: 0,
                min_occurrences: 3,
                ..Default::default()
            },
        );
        engine.ensure_tables().unwrap();
        // No episodes → no patterns → no proactive message
        let result = engine.generate_proactive().unwrap();
        assert!(result.is_none());
    }

    // ── Open-loop detector tests ─────────────────────────────────────────────

    /// Helper: create an OpenLoopDetector with an in-memory DB and a test session.
    /// Returns (detector, pool) so callers can insert episodes.
    fn test_detector() -> (OpenLoopDetector, SqlitePool) {
        let pool = storage::SqlitePool::open_memory().unwrap();
        // Create a session so foreign key works
        pool.with_conn(|conn| {
            conn.execute(
                "INSERT INTO sessions (id, channel) VALUES ('test-session', 'test')",
                [],
            )
            .unwrap();
            Ok(())
        })
        .unwrap();
        let config = OpenLoopConfig {
            scan_window_hours: 72,
            resolution_window_hours: 1, // 1 hour for easy testing
            max_reminders: 5,
        };
        let detector = OpenLoopDetector::new(pool.clone(), config);
        (detector, pool)
    }

    /// Insert a test episode with a given content and hours-ago timestamp.
    fn insert_episode(pool: &SqlitePool, id: &str, content: &str, hours_ago: i64) {
        let ts = (Utc::now() - chrono::Duration::hours(hours_ago)).to_rfc3339();
        pool.with_conn(|conn| {
            conn.execute(
                "INSERT INTO episodes (id, session_id, role, content, timestamp)
                 VALUES (?1, 'test-session', 'user', ?2, ?3)",
                rusqlite::params![id, content, ts],
            )
            .unwrap();
            Ok(())
        })
        .unwrap();
    }

    #[test]
    fn test_open_loop_no_episodes() {
        let (detector, _) = test_detector();
        let loops = detector.detect_open_loops().unwrap();
        assert!(loops.is_empty());
    }

    #[test]
    fn test_open_loop_unresolved_commitment() {
        let (detector, pool) = test_detector();
        // Commitment from 2 hours ago (beyond 1-hour resolution window)
        insert_episode(
            &pool,
            "e1",
            "I need to update the documentation for the API",
            2,
        );

        let loops = detector.detect_open_loops().unwrap();
        assert_eq!(loops.len(), 1);
        assert!(loops[0].topic.contains("update"));
        assert!(loops[0].topic.contains("documentation"));
    }

    #[test]
    fn test_open_loop_resolved_commitment() {
        let (detector, pool) = test_detector();
        // Commitment from 3 hours ago
        insert_episode(
            &pool,
            "e1",
            "I need to update the documentation for the API",
            3,
        );
        // Resolution — references same topic keywords + resolution marker
        insert_episode(
            &pool,
            "e2",
            "I finished the documentation update for the API",
            0, // recent
        );

        let loops = detector.detect_open_loops().unwrap();
        assert!(loops.is_empty(), "should be resolved, but got: {:?}", loops);
    }

    #[test]
    fn test_open_loop_too_recent_not_flagged() {
        let (detector, pool) = test_detector();
        // Commitment from 30 minutes ago — within the 1-hour resolution window
        let ts = (Utc::now() - chrono::Duration::minutes(30)).to_rfc3339();
        pool.with_conn(|conn| {
            conn.execute(
                "INSERT INTO episodes (id, session_id, role, content, timestamp)
                 VALUES ('e1', 'test-session', 'user', 'I need to review the pull request', ?1)",
                [&ts],
            )
            .unwrap();
            Ok(())
        })
        .unwrap();

        let loops = detector.detect_open_loops().unwrap();
        assert!(loops.is_empty(), "recent commitment should not be flagged");
    }

    #[test]
    fn test_open_loop_generate_reminders() {
        let (detector, pool) = test_detector();
        insert_episode(
            &pool,
            "e1",
            "I should refactor the authentication module",
            5,
        );

        let reminders = detector.generate_reminders().unwrap();
        assert_eq!(reminders.len(), 1);
        assert!(reminders[0].content.contains("Open loop"));
        assert!(reminders[0].content.contains("refactor"));
        assert!(reminders[0].triggered_by.starts_with("open_loop:"));
    }

    #[test]
    fn test_open_loop_max_reminders_cap() {
        let (detector, pool) = test_detector();
        // Insert more commitments than max_reminders (5)
        for i in 0..8 {
            insert_episode(
                &pool,
                &format!("e{i}"),
                &format!("I need to handle task_{i:04} in the project"),
                10 + i as i64,
            );
        }

        let loops = detector.detect_open_loops().unwrap();
        assert!(
            loops.len() <= 5,
            "should cap at max_reminders, got {}",
            loops.len()
        );
    }

    #[test]
    fn test_open_loop_assistant_messages_ignored() {
        let (detector, pool) = test_detector();
        // Insert an assistant message with commitment phrasing — should be ignored
        let ts = (Utc::now() - chrono::Duration::hours(5)).to_rfc3339();
        pool.with_conn(|conn| {
            conn.execute(
                "INSERT INTO episodes (id, session_id, role, content, timestamp)
                 VALUES ('e1', 'test-session', 'assistant', 'I will help you with that task', ?1)",
                [&ts],
            )
            .unwrap();
            Ok(())
        })
        .unwrap();

        let loops = detector.detect_open_loops().unwrap();
        assert!(loops.is_empty(), "assistant messages should be ignored");
    }

    #[test]
    fn test_open_loop_with_agent_attribution() {
        let (detector, pool) = test_detector();
        let ts = (Utc::now() - chrono::Duration::hours(5)).to_rfc3339();
        pool.with_conn(|conn| {
            conn.execute(
                "INSERT INTO episodes (id, session_id, role, content, timestamp, agent)
                 VALUES ('e1', 'test-session', 'user', 'I need to deploy the staging server', ?1, 'devops-agent')",
                [&ts],
            )
            .unwrap();
            Ok(())
        })
        .unwrap();

        let loops = detector.detect_open_loops().unwrap();
        assert_eq!(loops.len(), 1);
        assert_eq!(loops[0].agent.as_deref(), Some("devops-agent"));

        let reminders = detector.generate_reminders().unwrap();
        assert!(reminders[0].content.contains("devops-agent"));
    }

    // ── JSON parser tests ───────────────────────────────────────────────────

    fn sample_episodes() -> Vec<EpisodeRow> {
        vec![
            (
                "e0".into(),
                "I need to update the API docs".into(),
                "2024-01-01T10:00:00+00:00".into(),
                None,
            ),
            (
                "e1".into(),
                "The docs are done now".into(),
                "2024-01-02T15:00:00+00:00".into(),
                None,
            ),
            (
                "e2".into(),
                "I should fix the login bug".into(),
                "2024-01-03T09:00:00+00:00".into(),
                Some("dev-agent".into()),
            ),
        ]
    }

    #[test]
    fn test_parse_commitment_clean_json() {
        let episodes = sample_episodes();
        let json = r#"[{"index":2,"topic":"fix login bug","resolved":false}]"#;
        let loops = parse_commitment_response(json, &episodes, 5).unwrap();
        assert_eq!(loops.len(), 1);
        assert_eq!(loops[0].topic, "fix login bug");
        assert_eq!(loops[0].agent.as_deref(), Some("dev-agent"));
    }

    #[test]
    fn test_parse_commitment_embedded_json() {
        let episodes = sample_episodes();
        let raw = r#"Here are the results: [{"index":0,"topic":"update API docs","resolved":false}] done"#;
        let loops = parse_commitment_response(raw, &episodes, 5).unwrap();
        assert_eq!(loops.len(), 1);
        assert_eq!(loops[0].topic, "update API docs");
    }

    #[test]
    fn test_parse_commitment_resolved_filtered() {
        let episodes = sample_episodes();
        let json = r#"[{"index":0,"topic":"update docs","resolved":true},{"index":2,"topic":"fix bug","resolved":false}]"#;
        let loops = parse_commitment_response(json, &episodes, 5).unwrap();
        assert_eq!(loops.len(), 1);
        assert_eq!(loops[0].topic, "fix bug");
    }

    #[test]
    fn test_parse_commitment_empty_array() {
        let episodes = sample_episodes();
        let loops = parse_commitment_response("[]", &episodes, 5).unwrap();
        assert!(loops.is_empty());
    }

    #[test]
    fn test_parse_commitment_invalid() {
        let episodes = sample_episodes();
        assert!(parse_commitment_response("no json here", &episodes, 5).is_err());
    }

    #[test]
    fn test_parse_commitment_out_of_bounds_index() {
        let episodes = sample_episodes();
        let json = r#"[{"index":99,"topic":"nonexistent","resolved":false}]"#;
        let loops = parse_commitment_response(json, &episodes, 5).unwrap();
        assert!(loops.is_empty());
    }

    // ── Async tests ─────────────────────────────────────────────────────────

    #[tokio::test]
    async fn test_detect_async_no_llm_equals_sync() {
        let (detector, _) = test_detector();
        let sync_result = detector.detect_open_loops().unwrap();
        let async_result = detector.detect_open_loops_async().await.unwrap();
        assert_eq!(sync_result.len(), async_result.len());
    }

    // ── Mock LLM tests ─────────────────────────────────────────────────────

    struct MockLlm {
        response: String,
    }

    #[async_trait::async_trait]
    impl cortex::LlmProvider for MockLlm {
        async fn generate(
            &self,
            _messages: &[cortex::Message],
        ) -> Result<cortex::Response, cortex::LlmError> {
            Ok(cortex::Response {
                content: self.response.clone(),
                usage: None,
            })
        }

        async fn generate_stream(
            &self,
            _messages: &[cortex::Message],
        ) -> Result<
            std::pin::Pin<
                Box<
                    dyn futures::Stream<Item = Result<cortex::ResponseChunk, cortex::LlmError>>
                        + Send,
                >,
            >,
            cortex::LlmError,
        > {
            Err(cortex::LlmError::ProviderUnavailable("mock".to_string()))
        }

        async fn health_check(&self) -> bool {
            true
        }

        fn name(&self) -> &str {
            "mock"
        }
    }

    #[tokio::test]
    async fn test_detect_async_with_mock_llm() {
        let pool = storage::SqlitePool::open_memory().unwrap();
        pool.with_conn(|conn| {
            conn.execute(
                "INSERT INTO sessions (id, channel) VALUES ('test-session', 'test')",
                [],
            )
            .unwrap();
            Ok(())
        })
        .unwrap();

        // Insert a commitment
        let ts = (Utc::now() - chrono::Duration::hours(5)).to_rfc3339();
        pool.with_conn(|conn| {
            conn.execute(
                "INSERT INTO episodes (id, session_id, role, content, timestamp)
                 VALUES ('e1', 'test-session', 'user', 'I need to deploy the staging fix', ?1)",
                [&ts],
            )
            .unwrap();
            Ok(())
        })
        .unwrap();

        let mock = Arc::new(MockLlm {
            response: r#"[{"index":0,"topic":"deploy staging fix","resolved":false}]"#.to_string(),
        });

        let detector = OpenLoopDetector::with_llm(
            pool,
            OpenLoopConfig {
                scan_window_hours: 72,
                resolution_window_hours: 1,
                max_reminders: 5,
            },
            mock,
        );

        let loops = detector.detect_open_loops_async().await.unwrap();
        assert_eq!(loops.len(), 1);
        assert_eq!(loops[0].topic, "deploy staging fix");
    }

    #[tokio::test]
    async fn test_detect_async_llm_bad_json_falls_back() {
        let (_, pool) = test_detector();
        insert_episode(
            &pool,
            "e1",
            "I need to update the documentation for the API",
            2,
        );

        let mock = Arc::new(MockLlm {
            response: "Sorry, I can't understand the request".to_string(),
        });

        let detector = OpenLoopDetector::with_llm(
            pool,
            OpenLoopConfig {
                scan_window_hours: 72,
                resolution_window_hours: 1,
                max_reminders: 5,
            },
            mock,
        );

        let loops = detector.detect_open_loops_async().await.unwrap();
        // Should fallback to keyword detection and find the commitment
        assert_eq!(loops.len(), 1);
        assert!(loops[0].topic.contains("update"));
    }

    struct SlowMockLlm;

    #[async_trait::async_trait]
    impl cortex::LlmProvider for SlowMockLlm {
        async fn generate(
            &self,
            _messages: &[cortex::Message],
        ) -> Result<cortex::Response, cortex::LlmError> {
            tokio::time::sleep(tokio::time::Duration::from_secs(10)).await;
            Ok(cortex::Response {
                content: "[]".to_string(),
                usage: None,
            })
        }

        async fn generate_stream(
            &self,
            _messages: &[cortex::Message],
        ) -> Result<
            std::pin::Pin<
                Box<
                    dyn futures::Stream<Item = Result<cortex::ResponseChunk, cortex::LlmError>>
                        + Send,
                >,
            >,
            cortex::LlmError,
        > {
            Err(cortex::LlmError::ProviderUnavailable("mock".to_string()))
        }

        async fn health_check(&self) -> bool {
            true
        }

        fn name(&self) -> &str {
            "slow-mock"
        }
    }

    #[tokio::test]
    async fn test_detect_async_timeout_falls_back() {
        let (_, pool) = test_detector();
        insert_episode(
            &pool,
            "e1",
            "I need to update the documentation for the API",
            2,
        );

        let detector = OpenLoopDetector::with_llm(
            pool,
            OpenLoopConfig {
                scan_window_hours: 72,
                resolution_window_hours: 1,
                max_reminders: 5,
            },
            Arc::new(SlowMockLlm),
        );

        let loops = detector.detect_open_loops_async().await.unwrap();
        // Should timeout and fallback to keyword detection
        assert_eq!(loops.len(), 1);
        assert!(loops[0].topic.contains("update"));
    }

    #[tokio::test]
    async fn test_generate_reminders_async_formats_correctly() {
        let (_, pool) = test_detector();
        insert_episode(
            &pool,
            "e1",
            "I should refactor the authentication module",
            5,
        );

        let mock = Arc::new(MockLlm {
            response: r#"[{"index":0,"topic":"refactor auth module","resolved":false}]"#
                .to_string(),
        });

        let detector = OpenLoopDetector::with_llm(
            pool,
            OpenLoopConfig {
                scan_window_hours: 72,
                resolution_window_hours: 1,
                max_reminders: 5,
            },
            mock,
        );

        let reminders = detector.generate_reminders_async().await.unwrap();
        assert_eq!(reminders.len(), 1);
        assert!(reminders[0].content.contains("Open loop"));
        assert!(reminders[0].content.contains("refactor auth module"));
        assert!(reminders[0].triggered_by.starts_with("open_loop:"));
    }
}
