//! # Brain Ganglia (Basal Ganglia)
//!
//! Proactivity engine — habit detection and open-loop tracking.
//!
//! **Habit engine** detects behavioral patterns by bucketing episodic memory
//! into (keyword, day-of-week, hour) histograms.  When a pattern crosses the
//! occurrence threshold at the current time slot, and rate-limit / quiet-hour
//! gates pass, a proactive message is emitted.
//!
//! **Open-loop detector** finds unresolved commitments ("I need to …",
//! "remind me to …") in episodic memory and surfaces reminders.

pub mod habit;
pub mod openloop;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use thiserror::Error;

// ─── Errors ──────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum GangliaError {
    #[error("Storage error: {0}")]
    Storage(#[from] storage::sqlite::SqliteError),
}

// ─── Shared types ────────────────────────────────────────────────────────────

/// A recurring topic pattern detected in episodic memory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicPattern {
    /// The recurring keyword.
    pub topic: String,
    /// Day-of-week (0 = Monday, 6 = Sunday).
    pub day_of_week: u8,
    /// Hour-of-day bucket (0–23).
    pub hour: u8,
    /// Number of episodes that confirm this pattern.
    pub occurrences: usize,
    /// Originating agent for this pattern (if all occurrences are from one agent).
    pub agent: Option<String>,
}

/// A proactive message generated by the ganglia subsystem.
#[derive(Debug, Clone)]
pub struct ProactiveMessage {
    /// Message to surface to the user.
    pub content: String,
    /// The topic that triggered the message.
    pub triggered_by: String,
    /// Generation timestamp.
    pub created_at: DateTime<Utc>,
    /// Originating agent (if the pattern is agent-attributed).
    pub agent: Option<String>,
}

// ─── Re-exports ──────────────────────────────────────────────────────────────

pub use habit::{HabitConfig, HabitEngine};
pub use openloop::{OpenLoop, OpenLoopConfig, OpenLoopDetector};
