#!/usr/bin/env bash
# Emit the topological order in which the workspace's internal crates must
# be `cargo publish`-ed. Each crate must be published after all of its
# internal dependencies are on crates.io, or the upstream `cargo publish`
# resolver rejects the manifest.
#
# Usage:
#   ./scripts/publish-order.sh                # print order to stdout
#   ./scripts/publish-order.sh --regen-doc    # regenerate docs/PUBLISH_ORDER.md
#
# Source of truth is `cargo metadata`. Re-run after adding/removing any
# internal dependency.

set -euo pipefail

root_dir="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root_dir"

order="$(cargo metadata --format-version 1 --no-deps 2>/dev/null | python3 -c "
import json, sys
md = json.load(sys.stdin)
pkgs = {p['name']: p for p in md['packages']}
deps = {}
for name, p in pkgs.items():
    deps[name] = set()
    for d in p['dependencies']:
        if d['name'] in pkgs:
            deps[name].add(d['name'])
ordered = []
visited = set()
def visit(n):
    if n in visited:
        return
    visited.add(n)
    for d in sorted(deps[n]):
        visit(d)
    ordered.append(n)
for n in sorted(pkgs):
    visit(n)
print('\n'.join(ordered))
")"

if [ "${1:-}" = "--regen-doc" ]; then
    out="docs/PUBLISH_ORDER.md"
    {
        echo "# Brain OS — Publish Order"
        echo ""
        echo "> Auto-generated by \`scripts/publish-order.sh --regen-doc\`. Do not edit by hand."
        echo "> Last regenerated: $(date -u +%Y-%m-%d)."
        echo ""
        echo "Topological order in which internal crates must be \`cargo publish\`-ed."
        echo "Each crate must already have its dependencies on crates.io when its turn comes,"
        echo "or the resolver rejects the manifest."
        echo ""
        echo '```'
        echo "$order"
        echo '```'
        echo ""
        echo "Regenerate when any internal dependency is added or removed:"
        echo ""
        echo '```sh'
        echo "./scripts/publish-order.sh --regen-doc"
        echo '```'
    } > "$out"
    echo "Wrote $out ($(echo "$order" | wc -l | tr -d ' ') crates)."
else
    echo "$order"
fi
